ТаблицаЗначений в первом приближении
otymko/JOneS pull request #178
Opened 2022-10-10 20:27 UTC by dmpas

fix #20

2022-10-11 03:09 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/StandardTypeInitializer.java
> +import com.github.otymko.jos.runtime.context.type.collection.*;
@dmpas делал ребейс из девелопа? Я там код стала докинул. Импорты с * не используем =)

2022-10-11 06:38 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/StandardTypeInitializer.java
> +import com.github.otymko.jos.runtime.context.type.collection.*;
в воскресенье подтягивался вроде. Проморгал звёздочки...

2022-10-11 10:31 UTC, otymko requested changes

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +        this.data = new Hashtable<>();
@dmpas, почему именно Hashtable? Боишься null ключей? По идее, лучше HashMap, т.к. нам не нужна синхронизация здесь.

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionKey.java
> +    public static V8CollectionKey extract(List<IValue> fields, PropertyNameAccessor element) {
@dmpas статик методы лучше размещать до конструктора

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +public class V8CollectionIndex extends ContextValue {
@dmpas давай сразу jdoc писать, хоть в каком-то объеме.

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8KeyAndValue.java
> -                .sorted((valueOne, valueTwo) -> valueOne.getValue().compareTo(valueTwo.getValue()))
@dmpas почему? тесты с оскрипта сломались?

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
> +    public V8Array unloadColumnInternal(IValue columnIndex) {
@dmpas в классе есть методы интернал, которые либо паблик, либо в рамкам пакета видны. Давай их спрячем.

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +    private void setInternal(IValue index, IValue newValue) {
@dmpas давай выбросим исключение - непредвиденное состояние или что-то подобное

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +        if (name.asString().isEmpty()) {
@dmpas raw здесь не нужно?

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +    V8ValueTableColumn column;
@dmpas давай скроем в геттеры

2022-10-11 10:31 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +        final var direction = ruleElements.length < 2 ? ASC: getDirection(ruleElements[1]);
@dmpas давай обозначим, что именно значит 2

2022-10-11 13:19 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +        this.data = new Hashtable<>();
бес попутал. Я выпиливал везде Dictionary, здесь упустил, уберу.

2022-10-11 13:20 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +public class V8CollectionIndex extends ContextValue {
мои доки, моя печаль... Принял.

2022-10-11 13:21 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8KeyAndValue.java
> -                .sorted((valueOne, valueTwo) -> valueOne.getValue().compareTo(valueTwo.getValue()))
они разве с оскрипта? Там сломался только один, который сравнивал выхлоп скрипта. И он опирался на порядок обхода. Можно было тест подкостылить - порядок в нём поменять, но по факту-то тест на неправильное поведение.

2022-10-11 13:21 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
> +    public V8Array unloadColumnInternal(IValue columnIndex) {
Принято.

2022-10-11 13:22 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +    private void setInternal(IValue index, IValue newValue) {
Не понял, на каком конкретно месте?

2022-10-11 13:23 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +    V8ValueTableColumn column;
Оно по идее вообще скрыто, нет? Ему не нужен геттер

2022-10-11 13:23 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +        final var direction = ruleElements.length < 2 ? ASC: getDirection(ruleElements[1]);
угу

2022-10-11 13:38 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +    V8ValueTableColumn column;
Класс обозначен как `@Value` - поля уже private

2022-10-11 13:42 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +        if (name.asString().isEmpty()) {
для `asString()` не обязательно. Все контейнеры перебрасывают вызов в свой вложенный value

2022-10-11 18:26 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +public class V8CollectionIndex extends ContextValue {
Достаточно хотя бы для самих классов

2022-10-11 18:27 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +    V8ValueTableColumn column;
Да, упустил. Спасибо

2022-10-12 05:38 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8KeyAndValue.java
> -                .sorted((valueOne, valueTwo) -> valueOne.getValue().compareTo(valueTwo.getValue()))
Оки

2022-10-12 05:38 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +    private void setInternal(IValue index, IValue newValue) {
кажется не туда, потом еще раз просмотрю и напишу, если увижу

2022-10-12 14:35 UTC, otymko requested changes

2022-10-12 14:35 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionKey.java
> +class V8CollectionKey {
@dmpas, jdoc?

2022-10-12 14:35 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
> +        // var index = inputIndex.getRawValue().asNumber().intValue();
@dmpas, закомментированный код

2022-10-12 14:35 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
> +    private int indexOfRow(IValue row) {
@dmpas, ковертаци значения IValue здесь не получится?

2022-10-12 14:35 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableSortRule.java
> +    V8ValueTableColumn column;
@dmpas, филы до методов

2022-10-12 14:36 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionKey.java
> +class V8CollectionKey {
@otymko  inner же ?

2022-10-12 14:38 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
> +    private int indexOfRow(IValue row) {
не, тут всё в порядке. На вход может прилететь два типа, на выход строго инт.
метод внутренний, не маршаллится

2022-10-12 14:54 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionKey.java
> +class V8CollectionKey {
Ладно, забьем пока на inner

2022-10-12 14:56 UTC, otymko approved these changes

2022-10-12 15:01 UTC, merged