Индексы коллекции
otymko/JOneS pull request #225
Opened 2022-10-24 07:13 UTC by dmpas

2022-10-24 12:59 UTC, otymko requested changes

2022-10-24 12:59 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/IndexSourceCollection.java
> +    void indexAdded(V8CollectionIndex index);
@dmpas ну раз делаем у методов выше, то давай сюда тоже javadoc

2022-10-24 12:59 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/IndexSourceCollection.java
> +    void indexAdded(V8CollectionIndex index);
Ну и странное имя метода. Можешь расшифровать?

2022-10-24 12:59 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +        throw MachineException.getPropertyIsNotWritableException("");
@dmpas а какой текст исключения в итоге?

2022-10-24 12:59 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndexes.java
> +            ((V8CollectionIndex)index).clear();
@dmpas, зачем? На внутренние "V8CollectionIndex" где-то могут еще ссылаться?

2022-10-24 12:59 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableColumnCollection.java
> +        final var columnNames = columnList.split(",");
@dmpas паттерн в константы

2022-10-24 12:59 UTC, otymko commented on engine/src/test/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTableIndexTest.java
> +public class V8ValueTableIndexTest extends BaseScriptTest {
@dmpas, кстати, public можно в таких классах не писать. жюнит их подхватит

2022-10-24 13:40 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/IndexSourceCollection.java
> +    void indexAdded(V8CollectionIndex index);
@otymko событие `индекс добавлен`.

2022-10-24 13:41 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndexes.java
> +            ((V8CollectionIndex)index).clear();
@otymko да, ты можешь в прикладном коде написать `Индекс = Т.Индексы[0];` и у тебя будет ссылка на Индекс.

2022-10-24 14:00 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndexes.java
> +            ((V8CollectionIndex)index).clear();
В оскрипте такое же поведение?

2022-10-24 14:01 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndexes.java
> +            ((V8CollectionIndex)index).clear();
@otymko в ОСкрипте индексы не используются.

2022-10-25 13:21 UTC, otymko approved these changes

2022-10-25 13:22 UTC, merged

2022-11-16 08:10 UTC, nixel2007 commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +        return new ArrayList<>();
Оно разве не должно быть неизменяемым?

2022-11-16 08:10 UTC, nixel2007 commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
>      @ContextMethod(name = "Удалить", alias = "Delete")
En алиас?

2022-11-16 08:12 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueTable.java
>      @ContextMethod(name = "Удалить", alias = "Delete")
алиас как-раз Delete.
Решили, что внутренне методы именуем java-style - везде remove в джаве
альясы - честные оскриптовые, там Delete

2022-11-16 08:12 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8CollectionIndex.java
> +        return new ArrayList<>();
Возможно.