WIP: #19 Релизовал тип СписокЗначений
otymko/JOneS pull request #229
Opened 2022-10-28 14:41 UTC by APonkratov

Конструкторы:
- [X]  По умолчанию

Свойства:
- [ ]  Доступные значения
- [ ]  ТипЗначения

Методы:
- [X] Вставить
- [ ]  ~~ВыбратьЭлементы~~ - интерактивное действие
- [ ]  ВыгрузитьЗначения
- [X]  Добавить
- [X]  ЗагрузитьЗначения
- [X]  ЗаполнитьПометки
- [X]  Индекс
- [X]  Количество
- [X]  НайтиПоЗначению
- [ ]  НайтиПоИдентификатору
- [ ]  ~~ОтметитьЭлементы~~ - интерактивное действие
- [X]  Очистить
- [X]  Получить
- [X]  Сдвинуть
- [X]  Скопировать
- [ ]  СортироватьПоЗначению
- [ ]  СортироватьПоПредставлению
- [X]  Удалить

2022-10-28 14:49 UTC, dmpas requested changes

2022-10-28 14:49 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public V8ValueListItem add(IValue value, String presentation, BooleanValue check, IValue picture) {
Вместо `BooleanValue` лучше взять джавовский `Boolean` (не `boolean`)

2022-10-28 14:49 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +        final var intOffset = offset.getRawValue().asNumber().intValue();
можно `offset` в таком случае сразу `int` сделать, думаю

2022-10-28 14:49 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    public static V8ValueListItem constructor(V8ValueList owner, IValue value, String presentation, BooleanValue check, IValue picture) {
у этого объекта не должно быть контекст-конструктора.
Он же не создаётся из прикладного кода.

2022-10-28 14:49 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private BooleanValue check;
Лучше сделать джавовский `Boolean`

2022-10-28 17:58 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public V8ValueListItem add(IValue value, String presentation, BooleanValue check, IValue picture) {
Done

2022-10-28 17:58 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +        final var intOffset = offset.getRawValue().asNumber().intValue();
Done

2022-10-28 17:59 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    public static V8ValueListItem constructor(V8ValueList owner, IValue value, String presentation, BooleanValue check, IValue picture) {
Done

2022-10-28 17:59 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private BooleanValue check;
Done

2022-10-29 12:34 UTC, otymko commented
@APonkratov большое спасибо за вклад в проект! По ревью сейчас посмотрю, может есть моменты, которые можно сделать лучше.

2022-10-29 12:55 UTC, otymko requested changes

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +package com.github.otymko.jos.runtime.context.type.collection;
@APonkratov, check не пройдет, не хватает лицензии и в хедере. С этим поможет команда `gradlew updateLicenses`

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public V8ValueList() {
@APonkratov, нужен публичный конструктор? Если нигде не используется вне класса, то давай его private.

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    private final List<IValue> values;
@APonkratov, если я правильно помню, можно здесь сузить тип до `List<V8ValueListItem>`, т.к. ничего другого внутри нет.

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    private final List<IValue> values;
Соответственно убрать ниже пару кастов в V8ValueListItem

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +                final var itemIndex = Integer.parseInt(castedItem.asString());
@APonkratov, можно использовать `castedItem.asNumber()`, внутри как раз реализовано, как здесь написано с выбросом `MachineException.convertToNumberException`

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public ContextInfo getContextInfo() {
@APonkratov, public методы бы поднять выше private, так удобнее в коде потом ориентироваться. А так, получается небольшой разрыв

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +package com.github.otymko.jos.runtime.context.type.collection;
лицензия

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private Boolean check;
@APonkratov, здесь может быть null? Если нет - давай в boolean переделаем

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private IValue picture;
@APonkratov, по поводу картинки, мы хотим ее поддерживать? Если да - то какой будет тип? В v8 это "Картинка", а в оскрипте как?

2022-10-29 12:55 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    public V8ValueListItem(V8ValueList owner, IValue value, String presentation, Boolean check, IValue picture) {
@APonkratov, private конструктор, если его не нужно использовать во вне. По сигнатуре совпадает с методом `constructor`.

2022-10-29 12:55 UTC, otymko commented on engine/src/test/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListTest.java
> +package com.github.otymko.jos.runtime.context.type.collection;
лицензия

2022-10-29 13:10 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    private final List<IValue> values;
@otymko а оно в итератор съестся нормально?

2022-10-29 15:43 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    private final List<IValue> values;
Хм, не факт, надо конвертер посмотреть)

2022-10-30 14:52 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private IValue picture;
В оскрипте, как я понял, картинка может быть чем угодно. Я предлагаю её оставить с целью сохранения совместимости.

2022-10-30 15:14 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +                final var itemIndex = Integer.parseInt(castedItem.asString());
ок, поправил

2022-10-30 15:26 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public V8ValueList() {
на первый взгляд не нужен. Сделал private

2022-10-30 15:27 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public ContextInfo getContextInfo() {
ок

2022-10-30 15:27 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private Boolean check;
не может. Пустое значение инициируется в FALSE

2022-10-30 15:27 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    public V8ValueListItem(V8ValueList owner, IValue value, String presentation, Boolean check, IValue picture) {
Сделал private

2022-10-31 11:57 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    private final List<IValue> values;
Пока оставим как есть

2022-10-31 11:58 UTC, otymko commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private Boolean check;
@APonkratov так может просто boolean? Зачем нам 3 состояния?

2022-11-01 14:06 UTC, APonkratov commented on engine/src/test/resources/tests/ValueList.os
> +	юТест.ПроверитьИстину(ПроверитьПорядок(СЗ, "аааааа", "аааааб", "Бааааа"), "Сортировка по регистру");
@otymko @dmpas  этот тест падает. Не могу вкурить где нужно подкрутить, чтобы сравнение строк происходило с учетом регистра. И нужно ли вообще это делать

2022-11-01 14:06 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueListItem.java
> +    private Boolean check;
поправил

2022-11-03 13:40 UTC, dmpas commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public void fillChecks(Boolean check) {
здесь можно обычный `boolean`

2022-11-03 13:40 UTC, dmpas approved these changes

2022-11-03 13:53 UTC, otymko commented on engine/src/test/resources/tests/ValueList.os
> +	юТест.ПроверитьИстину(ПроверитьПорядок(СЗ, "аааааа", "аааааб", "Бааааа"), "Сортировка по регистру");
Подкрутил

2022-11-03 14:29 UTC, otymko approved these changes

2022-11-03 14:30 UTC, otymko commented
@APonkratov ты закончил, что планировал? Если да - то я заливаю.

2022-11-03 14:41 UTC, APonkratov commented on engine/src/main/java/com/github/otymko/jos/runtime/context/type/collection/V8ValueList.java
> +    public void fillChecks(Boolean check) {
Done

2022-11-03 14:42 UTC, APonkratov commented
> @APonkratov ты закончил, что планировал? Если да - то я заливаю.

Теперь да. Влил последний фикс по комменту @dmpas

2022-11-03 15:54 UTC, merged